### PR TITLE
Make botkit-shell compatible with Node 4

### PR DESCRIPTION
**Pull request by erikzaadi**

### CODE REVIEW

**Comment by ben** [comment]
I like the idea! Let me know when you're ready for more review.

**Comment by djanowski** [comment]
Are there plans to release this? Node 4 is LTS so it would be nice to support it.

**Comment by ben** [comment]
It's not done yet. @erikzaadi, are you still interested in working on this?

**Comment by djanowski** [comment]
It works for me on Node 4, what's pending?

**Comment by ben** [comment]
Ah, I see. I never got an answer, so I never looked again. Sorry for the delay!

**Comment by erikzaadi** [comment]
@ben my bad, should have written that it's complete

**Comment by djanowski** [comment]
@ben Patch release? :)

**Comment by ben** [comment]
Whoops, sorry. v0.1.4 is up now. 😊

**Comment by djanowski** [comment]
@ben Thank you!

**Pull request merged**
